//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _272JABSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationReply
    {
        public int CRID { get; set; }
        public string Message { get; set; }
        public int UserID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Status { get; set; }
        public int ConversationID { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User User { get; set; }
    }
}
