//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _272JABSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReccomendedExcercise
    {
        public int ReccExcerciseID { get; set; }
        public int ExcerciseID { get; set; }
        public int UserID { get; set; }
    
        public virtual Excercis Excercis { get; set; }
        public virtual User User { get; set; }
    }
}
