//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _272JABSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCondition
    {
        public int UserConditionID { get; set; }
        public int ConditionTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual CondtionType CondtionType { get; set; }
        public virtual User User { get; set; }
    }
}
